/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
buildscript {
    repositories {
        jcenter()
    }
}

plugins {
    id("nebula.kotlin") version "1.2.41"
}

apply<ApplicationPlugin>()
configure<ApplicationPluginConvention> {
    mainClassName = "MainKt" // haha
}

repositories {
    jcenter()
}

dependencies {
    compile("me.drmaas:ratpack-kotlin-dsl:1.4.1")
}
